version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - node_exporter
      - blackbox

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"
    depends_on:
      - webhook

  webhook:
    build: ./webhook
    container_name: alert-webhook
    volumes:
      - ./ansible:/ansible
      - ./webhook:/webhook
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ANSIBLE_INVENTORY=/ansible/inventory.ini
      - ANSIBLE_PLAYBOOK=/ansible/restart-nginx.yml
    ports:
      - "5001:5001"

  nginx-demo:
    image: nginx:stable
    container_name: nginx-demo
    ports:
      - "8080:80"

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    ports:
      - "9115:9115"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"

